### PR TITLE
Aact 144 change study dates

### PR DESCRIPTION
**Pull request by tibbs001**

### CODE REVIEW

**Comment by garrettqmartin8** [comment]
👍

**Comment by tibbs001** [comment]
Just to be clear...  thumbs up means I'm ok to merge to master, correct?


(Probably a stupid question, but want to make 100% sure I'm not mucking things up.)


________________________________

**Comment by garrettqmartin8** [comment]
Yes, that's correct. But, it looks like there are tests failing and merge conflicts. I can go in and fix those later today if you'd like.

**Comment by tibbs001** [comment]
Thanks.  I'll check it.  No worries.





________________________________

**Pull request merged**
