### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by dmlond**
This branch makes it possible to develop/test the system using [docker](https://www.docker.com/). It includes a Docker.README.md with documentation on how to set up and run it in Docker.

Before merging to master, fetch the dockerize branch and make sure that you can continue to use it WITHOUT docker, as you have been using the master branch up to this point. It SHOULD still work. If it does, this branch should merge right into master.

### CODE REVIEW

**Comment by garrettqmartin8** [comment]
Just to be clear on the purpose here; Is this meant for potential contributors to be able to set up a dev environment quickly or as a possible option for deployment in the future? Just want to wary of adding technologies to the stack.

**Comment by dmlond** [comment]
this is meant to standardize the local development environment without requiring users to install postgresql v X, ruby v X, gems, etc. We would probably use a smaller, more secure docker image for deployment.

**Comment by garrettqmartin8** [comment]
Cool, looks good 👍

**Comment by dmlond** [comment]
were you able to pull it and run it the way you would normally run master, without docker? I want to make sure it does not interfere with your normal development workflow

**Comment by garrettqmartin8** [comment]
Yup, everything works without Docker in your branch. Thanks for making sure!

**Pull request merged**
